# Generated by Django 6.1.1 on 2026-09-27 22:29

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.avatar_upload_path),
        ),
    ]
