# Generated by Django 6.1.1 on 2026-09-28 00:40

import portal.models
import portal.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=portal.storage.avatar_storage, upload_to=portal.models.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=portal.storage.resume_storage, upload_to=portal.models.resume_upload_path),
        ),
    ]
