# Generated by Django 6.1.1 on 2026-09-28 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_profile_email_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_message_sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_message_text',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['to_user', 'status'], name='portal_conn_to_user_d8aba6_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['from_user', 'status'], name='portal_conn_from_us_178ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['connection', 'created_at'], name='portal_mess_connect_98236d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_professional', 'deactivated'], name='portal_prof_is_prof_540f7a_idx'),
        ),
    ]
