# Generated by Django 6.1.1 on 2026-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_scaling_fields_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professional_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
