"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_list(name, default):
    raw = os.environ.get(name)
    return [item.strip() for item in raw.split(",") if item.strip()] if raw else default


# Everything below is configured through environment variables (see
# .env.example). The defaults are for local development only.

# Off unless explicitly enabled, so a forgotten variable on a real server
# can never leave debug pages (stack traces, settings) switched on.
DEBUG = os.environ.get("DJANGO_DEBUG", "").lower() in ("1", "true", "yes")

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is not set. For local development put DJANGO_DEBUG=True "
            "in backend/.env; on a server set DJANGO_SECRET_KEY to a long random value."
        )
    SECRET_KEY = "django-insecure-local-development-only"

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", ["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "users",
    "portal",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not DEBUG:
    # Serves the admin's static files in production; runserver handles them in dev.
    MIDDLEWARE.insert(2, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get("DATABASE_URL"):
    DATABASES = {"default": dj_database_url.parse(os.environ["DATABASE_URL"], conn_max_age=600, conn_health_checks=True)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Email (notifications about new requests/messages). Development prints emails
# to the server log; on a server set EMAIL_HOST (and the other EMAIL_* values in
# .env.example) to send for real. Without it, notifications are simply off.
SMTP_HOST = os.environ.get("EMAIL_HOST", "")
if SMTP_HOST:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": SMTP_HOST,
                "port": int(os.environ.get("EMAIL_PORT", "587")),
                "username": os.environ.get("EMAIL_HOST_USER", ""),
                "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
                "use_tls": os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes"),
            },
        },
    }
elif DEBUG:
    MAILERS = {"default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"}}
else:
    MAILERS = {"default": {"BACKEND": "django.core.mail.backends.smtp.EmailBackend", "OPTIONS": {"host": "localhost"}}}
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "UPSA Portal <no-reply@localhost>")

# The website's origin(s), e.g. https://unitedpsa.org - not this backend's.
FRONTEND_ORIGINS = _env_list("FRONTEND_ORIGINS", ["http://localhost:3000"])

CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SSL_REDIRECT", "true").lower() in ("1", "true", "yes")
    SECURE_HSTS_SECONDS = 3600  # raise once HTTPS is confirmed working end to end

# Clerk owns auth on the frontend; Django only verifies its tokens.
# See CLERK_ISSUER in .env.example for where to find this value.
CLERK_ISSUER = os.environ.get("CLERK_ISSUER", "")
# Only used to look up a member's email address when notifying them (addresses
# are never stored here). Keep it secret; it's the same key the frontend uses.
CLERK_SECRET_KEY = os.environ.get("CLERK_SECRET_KEY", "")

# Where notification emails link to: the website, not this backend.
PORTAL_BASE_URL = (os.environ.get("PORTAL_BASE_URL") or FRONTEND_ORIGINS[0]).rstrip("/")
NOTIFICATIONS_ENABLED = bool(CLERK_SECRET_KEY) and (bool(SMTP_HOST) or DEBUG)
NOTIFICATIONS_ASYNC = True  # send in a background thread so requests aren't slowed down

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.clerk_auth.ClerkJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Rate limits per signed-in user. "user" is a generous overall cap (the
    # portal refreshes in the background, so it has to leave room for that);
    # the named scopes apply to writes on specific views. Counters live in
    # Django's cache, which is per server process by default, so with several
    # workers the effective limit is a little looser - fine for abuse protection.
    # (Signed-out traffic is rejected before throttling runs; limit that at
    # the host or a proxy such as Cloudflare.)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "portal.throttles.WriteScopedThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "600/min",
        "requests": "30/day",
        "messages": "60/min",
        "uploads": "20/hour",
    },
}

# Shared cache. Rate limits and the message-email cooldown live here, so with
# more than one server (or worker process) they only count correctly if every
# copy shares one cache. Set REDIS_URL for that; without it each process keeps
# its own in memory, which is fine for a single small server.
if os.environ.get("REDIS_URL"):
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.redis.RedisCache", "LOCATION": os.environ["REDIS_URL"]}}

# Uploads (resumes, profile photos). Local disk in development. Set the R2_*
# variables to store them in Cloudflare R2 instead, which is required on a
# real server since its disk is wiped on every deploy. See portal/storage.py.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

R2_ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID", "")
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "")
R2_PRIVATE_BUCKET = os.environ.get("R2_PRIVATE_BUCKET", "")  # resumes, never public
R2_PUBLIC_BUCKET = os.environ.get("R2_PUBLIC_BUCKET", "")  # profile photos
R2_PUBLIC_BASE_URL = os.environ.get("R2_PUBLIC_BASE_URL", "").rstrip("/")  # public URL of that bucket
R2_ENABLED = all(
    [R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_PRIVATE_BUCKET, R2_PUBLIC_BUCKET, R2_PUBLIC_BASE_URL]
)
if not DEBUG and not R2_ENABLED:
    import warnings

    warnings.warn("R2 storage is not configured: uploaded resumes and photos will not survive a redeploy.")

CLERK_AUTHORIZED_PARTIES = _env_list("CLERK_AUTHORIZED_PARTIES", FRONTEND_ORIGINS)